version: '3.8'

services:
  claude-chat:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 開発用サービス（オプション）
  claude-chat-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev